import sharp from 'sharp';
const [SRC,r0,r1,OUT,S]=[process.argv[2],+process.argv[3],+process.argv[4],process.argv[5],+(process.argv[6]||2)];
const TS=48;
const meta=await sharp(SRC).metadata();
const cols=Math.round(meta.width/TS);
const rows=r1-r0+1;
const M=34;
const region=await sharp(SRC).extract({left:0,top:r0*TS,width:meta.width,height:rows*TS}).resize(meta.width*S,rows*TS*S,{kernel:'nearest'}).extend({top:M,left:M,background:{r:25,g:25,b:35,alpha:1}}).toBuffer();
const W=meta.width*S+M,H=rows*TS*S+M;
let g='',lab='';
for(let c=0;c<=cols;c++) g+=`<line x1="${M+c*TS*S}" y1="${M}" x2="${M+c*TS*S}" y2="${H}" stroke="red" stroke-width="0.6"/>`;
for(let r=0;r<=rows;r++) g+=`<line x1="${M}" y1="${M+r*TS*S}" x2="${W}" y2="${M+r*TS*S}" stroke="red" stroke-width="0.6"/>`;
for(let c=0;c<cols;c++) lab+=`<text x="${M+c*TS*S+8}" y="${M-8}" font-size="15" fill="#fff" font-family="monospace">${c}</text>`;
for(let r=0;r<rows;r++) lab+=`<text x="2" y="${M+r*TS*S+24}" font-size="14" fill="#fff" font-family="monospace">${r0+r}</text>`;
await sharp(region).composite([{input:Buffer.from(`<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">${g}${lab}</svg>`),top:0,left:0}]).png().toFile(OUT);
console.log('ok',OUT,cols+'cols rows '+r0+'-'+r1);
