import sharp from 'sharp';
const [SRC,c0,r0,cN,rN,OUT,S]=[process.argv[2],+process.argv[3],+process.argv[4],+process.argv[5],+process.argv[6],process.argv[7],+(process.argv[8]||5)];
const TS=48;const cw=cN*TS,ch=rN*TS;
const region=await sharp(SRC).extract({left:c0*TS,top:r0*TS,width:cw,height:ch}).resize(cw*S,ch*S,{kernel:'nearest'}).toBuffer();
let g='',lab='';
for(let c=0;c<=cN;c++) g+=`<line x1="${c*TS*S}" y1="0" x2="${c*TS*S}" y2="${ch*S}" stroke="red" stroke-width="1.2"/>`;
for(let r=0;r<=rN;r++) g+=`<line x1="0" y1="${r*TS*S}" x2="${cw*S}" y2="${r*TS*S}" stroke="red" stroke-width="1.2"/>`;
for(let r=0;r<rN;r++)for(let c=0;c<cN;c++) lab+=`<text x="${c*TS*S+3}" y="${r*TS*S+15}" font-size="13" fill="#00e0ff" font-family="monospace" font-weight="bold">${c0+c},${r0+r}</text>`;
await sharp(region).composite([{input:Buffer.from(`<svg width="${cw*S}" height="${ch*S}" xmlns="http://www.w3.org/2000/svg">${g}${lab}</svg>`),top:0,left:0}]).png().toFile(OUT);
console.log('ok');
